version: '3.9'
services:
  mongopriority:
    image: mongo:latest
    ports:
      - "27017:27017"

  priority:
    image: priority:0.0.1
    ports:
      - "8080:8080"
    environment:
      - database=mongodb
      - springfox.documentation.swagger.v2.path=/api-docs
      - server.port=8080
      - spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
      - spring.jackson.date-format=com.sarfraz.priority.RFC3339DateFormat
      - spring.data.mongodb.priority.uri=mongodb://mongopriority:27017/priority
    depends_on:
      - mongopriority